---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Code Base

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      statuses: write
      contents: read
      packages: read

    steps:
      - name: Run PR Lint
        # https://github.com/ivuorinen/actions
        uses: ivuorinen/actions/pr-lint@7ad79268dba5d86a7ec07512519b9d985c5ef208 # v2026.09.08
